name: Testes Automáticos
on: [pull_request]  

jobs:
  testar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Instalar dependências
        run: pip install pytest
      - name: Rodar testes
        run: pytest